name: Build Gradle project

on:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run program with Gradle Wrapper
        run: ./gradlew run
        env:
          VK_USER_ID: ${{ secrets.VK_USER_ID }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
          VK_ACCESS_TOKEN: ${{ secrets.VK_ACCESS_TOKEN }}